spring:
  application:
    name: credit-appraisal-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 0                                                                                           # random port to avoid ports conflicts

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}       # random value to avoid instances_ids conflicts
    prefer-ip-address: true

ms:
  customer:
    name: customer-ms
    path: /customer
  card:
    name: card-ms
    path: /card

mq:
  queues:
    card-issuance: card-issuance

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log