spring:
  application:
    name: customer-ms

server:
  port: 0                                                                                           # random port to avoid ports conflicts

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@${EUREKA_HOST}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}       # random value to avoid instances_ids conflicts
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log